# Site settings
baseurl = "https://hugo-photo-fotoalbum-swart.vercel.app"
languageCode = "en-EN"
title = "The Day"
theme = "photo-grid"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"x

[params]
    # Meta
    no_exif = true
    title = "The Wedding"
    subtitle = "Belaria Resort"
    author = "Lumberg"
    description = "The beginning of the end!"
    keywords = "Wedding, Photo, Gallery"

    # Body background and  text color
    bodybgcolor = "#3d3d3d" #"#DADADB" #"#6A6C6E"#
    bodytextcolor = "#f2f2f2"

    # Footer text
    footertext = "Made with love by [Me](https://github.com/uvacoder/) Me. <br> (C) 2021"
